# -*- coding: utf-8 -*-
"""LAB05-DECISION TREE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MOEGB-6wu77WNPhOudttunemwxiwGy8d
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.metrics import accuracy_score, mean_squared_error, r2_score
from sklearn.tree import plot_tree

iris = datasets.load_iris()

X = iris.data
y = iris.target

print("Feature Names:", iris.feature_names)
print("Target Classes:", iris.target_names)

pd.DataFrame(X, columns=iris.feature_names).head()
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)
clf = DecisionTreeClassifier(criterion='entropy', random_state=42)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

plt.figure(figsize=(12,8))
plot_tree(clf, feature_names=iris.feature_names,
          class_names=iris.target_names,
          filled=True)
plt.show()

housing = datasets.fetch_california_housing()

X = housing.data
y = housing.target

print("Feature Names:", housing.feature_names)

pd.DataFrame(X, columns=housing.feature_names).head()

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)


reg = DecisionTreeRegressor(random_state=42)
reg.fit(X_train, y_train)
y_pred = reg.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Squared Error:", mse)
print("R2 Score:", r2)
plt.figure()
plt.scatter(y_test, y_pred)
plt.xlabel("Actual Prices")
plt.ylabel("Predicted Prices")
plt.title("Actual vs Predicted Housing Prices")
plt.show()