# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XdCeJCn5mMleaOnch0JhkB-35WPu4BiN
"""

# Random Forest using Iris Dataset

# Step 1: Import libraries
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

# Step 2: Load Iris dataset
iris = load_iris()
X = iris.data
y = iris.target

# Step 3: Convert to DataFrame for display
df = pd.DataFrame(X, columns=iris.feature_names)
df['target'] = y

print("Sample Dataset:")
print(df.head())

# Step 4: Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Step 5: Create Random Forest model
model = RandomForestClassifier(n_estimators=100, random_state=42)

# Step 6: Train the model
model.fit(X_train, y_train)

# Step 7: Predict test results
y_pred = model.predict(X_test)

# Step 8: Evaluate model
accuracy = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

# Step 9: Display results
print("\nPredicted Values:")
print(y_pred)

print("\nConfusion Matrix:")
print(cm)

print("\nAccuracy:")
print(accuracy)